# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: Simpleapp
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mphasisdb2
    username: root
    password: root@39
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8083
logging:
  level:
    root: info
    com:
      example:
        Simpleapp: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} %msg%n'
  file:
    name: logs/empapp.log
